### ISSUE TITLE
LessThan, LessThanOrEqual,  GreaterThan, GreaterThanOrEqual

### ISSUE THREAD

**Issue by vanodevium** [hashicorp/go-set#37]
Do you have any plans to make such methods for TreeSet?
Because very often such methods are necessary.

If not, please provide a code example of the fastest way to implement such functionality.

> For example: I have treeset **(10, 20, 30, 40, 50)** and when I call **orderedSet.LessThan(30)** I will retrieve **20** , but for **orderedSet.GreaterThan(30)** I will retrieve **40**

Thanx!

**Comment by shoenig** [comment]
Hi @vanodevium! Indeed such methods would be very useful to add, it just wasn't something we needed right away. I can probably find time to work on this in the next few weeks, if you or someone else doesn't want to work on it first. 

The implementation(s) would be quite similar to the TopK/BottomK methods, but with slightly adjusted logic.

**Comment by vanodevium** [comment]
@shoenig 

Thank you very much for your response!

I already tried to do it, but my knowledge was not enough.

I will wait when you have free time.
