### ISSUE TITLE
iterator method of treeSet has  goroutine leaks

### ISSUE THREAD

**Issue by zonewave** [hashicorp/go-set#52]
I use "goleak" to detector  leak:
```golang
	t.Run("diff set", func(t *testing.T) {
		defer goleak.VerifyNone(t)
		t1 := TreeSetFrom[int, Compare[int]]([]int{1, 2, 3}, Cmp[int])
		t2 := TreeSetFrom[int, Compare[int]]([]int{4, 5, 6}, Cmp[int])
		must.False(t, t1.Subset(t2))
	})
```
if not iter all node, the channel will  block
<img width="581" alt="image" src="https://user-images.githubusercontent.com/26363539/235344574-34d0ac00-7426-4a19-9945-261418455e8f.png">

**Comment by shoenig** [comment]
Good catch, I had been thinking about ways to iterate 2 trees (for the `.Equal` and `.Subset` cases) without the use of goroutines, but after so many years of programming in Go using goroutines is just easier. 

If we could eliminate the use of goroutines though, that would be even better!
