### ISSUE TITLE
Why isn't `Set` recommended to be used with pointers?

### ISSUE THREAD

**Issue by efulmo** [hashicorp/go-set#70]
Documentation for `set.New()` says
> T must *not* be of pointer type, nor contain pointer fields, which are comparable
> but not in the way you expect. For these types, use HashSet instead.

It's a confusing statement. I use `Set` with addresses to a struct that has some pointer fields and it works just fine - it keeps unique pointers in the set. As far I understand from the source code, `Set` has no limitations for pointers or structs with pointers, it just _may work_ in unobvious way for unexperienced developers that don't understand difference between address comparison and deep struct comparison. `README` explains this aspect better.

**Comment by shoenig** [comment]
Hi @efulmo, you're correct in that a `Set` can be used with pointers or structs containing pointers as long as the `pointer` comparability is what you're actually expecting. When I wrote that doc string I was thinking about our main use case, where it's common to use a `.Equal` method for comparing equality of complex structs, where the behavior of pointer comparisons is wrong.

e.g.
https://play.golang.com/p/PPD110sXh9h

So yeah, the doc should be tweaked to be more accurate like the README. Would you be willing to open up a PR?

**Comment by shoenig** [comment]
Closed by #74
