### ISSUE TITLE
v3: a breaking changes release 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/go-set#90]
Less dramatic than the `v2` version, a `v3` would let us
- clean up some now deprecated parts described in https://github.com/hashicorp/go-set/pull/89
- eliminate `ForEach` in favor of an iterator used with the `range` keyword https://github.com/hashicorp/go-set/pull/82
- make any other breaking changes

**Comment by costela** [comment]
do you think more work in the direction started in #87 may be appropriate here as well?

**Comment by shoenig** [comment]
Hi @costela, to be honest I'm not sure what the fix would even look like. How about opening another issue so it can be tracked there?

As for the `v3` release I think the key feature is being able to use `range`; if we have more breaking changes in the future there's no reason we couldn't do a `v4`.

**Comment by shoenig** [comment]
https://github.com/hashicorp/go-set/releases/tag/v3.0.0
